#
# Cargo.toml
#

[package]
name         = "srcmake"
version      = "0.1.0"
authors      = ["Michael Furlong"]
description  = "A templated source code generator."
readme       = "readme.md"
edition      = "2021"

[dependencies]
chrono     = "0.4.22"
num-traits = "0.2.15"
